### ISSUE TITLE
Github action cannot build on Windows with OpenSSL

### ISSUE THREAD

**Issue by Hugal31** [Hugal31/yara-rust#113]
We get this error : `  D:\a\yara-rust\yara-rust\target\debug\build\yara-sys-a7d675839598f617\out\yara\libyara\crypto.h(38): fatal error C1083: Cannot open include file: 'openssl/crypto.h': No such file or directory`

Both on https://github.com/Hugal31/yara-rust/actions/runs/4627586826/jobs/8185675294?pr=108 and https://github.com/Hugal31/yara-rust/actions/runs/4627507725/jobs/8185510282.
But it worked fine on Yara 4.3.0 [PR](https://github.com/Hugal31/yara-rust/actions/runs/4622607795/jobs/8175491018), and [nothing relevant changed since](https://github.com/Hugal31/yara-rust/compare/c2c30a9..v0.19.0).

**Comment by Hugal31** [comment]
OpenSSL disabled on Windows for now in #108.

**Comment by vthib** [comment]
Not sure why it worked before and suddently didn't work, but I think adding YARA_OPENSSL_DIR instead of OPENSSL_DIR should solve the issue. I had the same issue on updating to yara-rust 0.19 and adding YARA_OPENSSL_DIR fixed it: https://github.com/vthib/boreal/pull/31/files
