### PR TITLE
Support Yara 3.10, link to default Yara package dependencies

### PR DESCRIPTION
**Pull request by pwrdwnsys**
* Reworked `build.rs` to support macOS, Linux, and now OpenBSD
* Static link to all dependencies needed by typical Yara package (cuckoo needs jansson, file needs magic)
* Update docs and links to reflect Yara 3.10

### CODE REVIEW

**Comment by r3dlight** [comment]
@pwrdwns, no feedback ? 
Can you update to bindgen version 0.50.0 ?

**Comment by Hugal31** [comment]
I am not confident it continuing this pull request by myself, as I cannot test on MacOS and FreeBSD. However I plan to update this crate to Rust 2018 and see if I can support Yara 3.10. @r3dlight, you wrote `Yara =< 3.10`, so are you concerned about compatibility with versions before 3.10?

**Comment by r3dlight** [comment]
@Hugal31 , I'm not really concerned about compatibility for old versions. As long as it works on linux, it's ok for me :) 3.10 or even 3.11 support would be highly appreciated !

**Comment by r3dlight** [comment]
Hi @Hugal31, can you help me fixing these issues when I'm compiling yara-sys ?

error[E0277]: `YR_NAMESPACE__bindgen_ty_1` doesn't implement `std::fmt::Debug`
   --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:706:5
    |
706 |     pub __bindgen_anon_1: YR_NAMESPACE__bindgen_ty_1,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_NAMESPACE__bindgen_ty_1` cannot be formatted using `{:?}`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `YR_NAMESPACE__bindgen_ty_1`
    = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_NAMESPACE__bindgen_ty_1`
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_META__bindgen_ty_1` doesn't implement `std::fmt::Debug`
   --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:778:5
    |
778 |     pub __bindgen_anon_1: YR_META__bindgen_ty_1,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_META__bindgen_ty_1` cannot be formatted using `{:?}`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `YR_META__bindgen_ty_1`
    = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_META__bindgen_ty_1`
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_META__bindgen_ty_2` doesn't implement `std::fmt::Debug`
   --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:779:5
    |
779 |     pub __bindgen_anon_2: YR_META__bindgen_ty_2,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_META__bindgen_ty_2` cannot be formatted using `{:?}`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `YR_META__bindgen_ty_2`
    = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_META__bindgen_ty_2`
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_MATCHES__bindgen_ty_1` doesn't implement `std::fmt::Debug`
   --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:902:5
    |
902 |     pub __bindgen_anon_1: YR_MATCHES__bindgen_ty_1,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_MATCHES__bindgen_ty_1` cannot be formatted using `{:?}`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `YR_MATCHES__bindgen_ty_1`
    = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_MATCHES__bindgen_ty_1`
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_MATCHES__bindgen_ty_2` doesn't implement `std::fmt::Debug`
   --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:903:5
    |
903 |     pub __bindgen_anon_2: YR_MATCHES__bindgen_ty_2,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_MATCHES__bindgen_ty_2` cannot be formatted using `{:?}`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `YR_MATCHES__bindgen_ty_2`
    = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_MATCHES__bindgen_ty_2`
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_STRING__bindgen_ty_1` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1013:5
     |
1013 |     pub __bindgen_anon_1: YR_STRING__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_STRING__bindgen_ty_1` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_STRING__bindgen_ty_1`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_STRING__bindgen_ty_1`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_STRING__bindgen_ty_2` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1014:5
     |
1014 |     pub __bindgen_anon_2: YR_STRING__bindgen_ty_2,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_STRING__bindgen_ty_2` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_STRING__bindgen_ty_2`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_STRING__bindgen_ty_2`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_STRING__bindgen_ty_3` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1015:5
     |
1015 |     pub __bindgen_anon_3: YR_STRING__bindgen_ty_3,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_STRING__bindgen_ty_3` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_STRING__bindgen_ty_3`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_STRING__bindgen_ty_3`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_STRING__bindgen_ty_4` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1016:5
     |
1016 |     pub __bindgen_anon_4: YR_STRING__bindgen_ty_4,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_STRING__bindgen_ty_4` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_STRING__bindgen_ty_4`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_STRING__bindgen_ty_4`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_RULE__bindgen_ty_1` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1279:5
     |
1279 |     pub __bindgen_anon_1: YR_RULE__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_RULE__bindgen_ty_1` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_RULE__bindgen_ty_1`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_RULE__bindgen_ty_1`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_RULE__bindgen_ty_2` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1280:5
     |
1280 |     pub __bindgen_anon_2: YR_RULE__bindgen_ty_2,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_RULE__bindgen_ty_2` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_RULE__bindgen_ty_2`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_RULE__bindgen_ty_2`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_RULE__bindgen_ty_3` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1281:5
     |
1281 |     pub __bindgen_anon_3: YR_RULE__bindgen_ty_3,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_RULE__bindgen_ty_3` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_RULE__bindgen_ty_3`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_RULE__bindgen_ty_3`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_RULE__bindgen_ty_4` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1282:5
     |
1282 |     pub __bindgen_anon_4: YR_RULE__bindgen_ty_4,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_RULE__bindgen_ty_4` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_RULE__bindgen_ty_4`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_RULE__bindgen_ty_4`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_RULE__bindgen_ty_5` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1283:5
     |
1283 |     pub __bindgen_anon_5: YR_RULE__bindgen_ty_5,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_RULE__bindgen_ty_5` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_RULE__bindgen_ty_5`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_RULE__bindgen_ty_5`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_EXTERNAL_VARIABLE__bindgen_ty_1` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1559:5
     |
1559 |     pub value: YR_EXTERNAL_VARIABLE__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_EXTERNAL_VARIABLE__bindgen_ty_1` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_EXTERNAL_VARIABLE__bindgen_ty_1`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_EXTERNAL_VARIABLE__bindgen_ty_1`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `YR_EXTERNAL_VARIABLE__bindgen_ty_2` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1560:5
     |
1560 |     pub __bindgen_anon_1: YR_EXTERNAL_VARIABLE__bindgen_ty_2,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `YR_EXTERNAL_VARIABLE__bindgen_ty_2` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `YR_EXTERNAL_VARIABLE__bindgen_ty_2`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&YR_EXTERNAL_VARIABLE__bindgen_ty_2`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `RE_NODE__bindgen_ty_1` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1710:5
     |
1710 |     pub __bindgen_anon_1: RE_NODE__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `RE_NODE__bindgen_ty_1` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `RE_NODE__bindgen_ty_1`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&RE_NODE__bindgen_ty_1`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `RE_NODE__bindgen_ty_2` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:1711:5
     |
1711 |     pub __bindgen_anon_2: RE_NODE__bindgen_ty_2,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `RE_NODE__bindgen_ty_2` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `RE_NODE__bindgen_ty_2`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&RE_NODE__bindgen_ty_2`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: `pthread_mutex_t` doesn't implement `std::fmt::Debug`
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:2103:5
     |
2103 |     pub mutex: YR_MUTEX,
     |     ^^^^^^^^^^^^^^^^^^^ `pthread_mutex_t` cannot be formatted using `{:?}`
     |
     = help: the trait `std::fmt::Debug` is not implemented for `pthread_mutex_t`
     = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&pthread_mutex_t`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: arrays only have std trait implementations for lengths 0..=32
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:2233:5
     |
2233 |     pub top_ac_match_list_lengths: [u32; 100usize],
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::array::LengthAtMost32` is not implemented for `[u32; 100]`
     |
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `[u32; 100]`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[u32; 100]`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0277]: arrays only have std trait implementations for lengths 0..=32
    --> /home/stefek/dev/rust/leguichet/target/debug/build/yara-sys-5dc675902db0a5a9/out/bindings.rs:2234:5
     |
2234 |     pub ac_match_list_length_pctls: [u32; 101usize],
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::array::LengthAtMost32` is not implemented for `[u32; 101]`
     |
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `[u32; 101]`
     = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[u32; 101]`
     = note: required for the cast to the object type `dyn std::fmt::Debug`

error: aborting due to 21 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `yara-sys`.

**Comment by Hugal31** [comment]
Hi,

I never seen this error before, and I cannot reproduce. Did you searched on bindgen issues ?
What is your configuration/OS/library versions ?

I am slowly adding support to newer versions of Yara.

**Comment by r3dlight** [comment]
I'm using bindgen v0.52.0 (I basically just updated your cargo.toml) / debian testing, I'll keep you in touch if I manage to fix it up :)
Great, many thanks for keeping on maintaining your crate !

**Comment by Hugal31** [comment]
The 0.3.0 version support up to Yara 3.11.0 !
However it does not have the new features from Yara 3.8.0 and onward.
